AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  CloudFormation template provisioning a versioned S3 bucket and CloudFront distribution
  for the math visuals static site, routing selected paths to an API Gateway origin.

Parameters:
  SiteEnvironmentName:
    Type: String
    Default: prod
    Description: Short environment identifier used for tagging (e.g. prod, dev).
  SiteBucketName:
    Type: String
    Description: Globally-unique name for the S3 bucket hosting the static site.
  ApiGatewayDomainName:
    Type: String
    Description: >-
      Fully-qualified domain name of the API Gateway stage (for example,
      a1b2c3d4.execute-api.us-east-1.amazonaws.com).
  ApiGatewayOriginPath:
    Type: String
    Default: ""
    AllowedPattern: '^$|^/.*$'
    ConstraintDescription: Origin paths must be blank or start with '/'.
    Description: Optional origin path appended to the API Gateway domain (e.g., /prod).
  CloudFrontPriceClass:
    Type: String
    Default: PriceClass_100
    AllowedValues:
      - PriceClass_100
      - PriceClass_200
      - PriceClass_All
    Description: Price class to use for the CloudFront distribution.
  CachePolicyId:
    Type: String
    Default: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
    AllowedPattern: '[-a-z0-9]+'
    Description: >-
      CloudFront cache policy ID applied to API-backed cache behaviors
      (defaults to the managed "CachingDisabled" policy).
  SharedParametersStackName:
    Type: String
    Description: Name of the CloudFormation stack that exports shared parameter names.

Conditions:
  HasApiGatewayOriginPath: !Not [!Equals [!Ref ApiGatewayOriginPath, ""]]

Resources:
  SiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SiteBucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: !Ref SiteEnvironmentName

  SiteOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access identity for math visuals static assets bucket

  SiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontOriginAccessIdentityReadOnly
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt SiteOriginAccessIdentity.S3CanonicalUserId
            Action:
              - s3:GetObject
            Resource: !Sub '${SiteBucket.Arn}/*'

  ApiOriginRequestPolicy:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub '${AWS::StackName}-api-origin-request-policy'
        Comment: Forward all query strings required by API Gateway path parameters
        CookiesConfig:
          CookieBehavior: none
        HeadersConfig:
          HeaderBehavior: none
        QueryStringsConfig:
          QueryStringBehavior: all

  ViewerRequestRouterFunction:
    Type: AWS::CloudFront::Function
    Properties:
      Name: !Sub '${AWS::StackName}-viewer-router'
      AutoPublish: true
      FunctionConfig:
        Comment: Rewrite friendly routes to their HTML assets
        Runtime: cloudfront-js-1.0
      FunctionCode: |
        'use strict';

        function normalizeAlias(value) {
          if (typeof value !== 'string' || !value) {
            return null;
          }
          var alias = value;
          if (alias.charCodeAt(0) !== 47) {
            alias = '/' + alias;
          }
          alias = alias.toLowerCase();
          if (alias.length > 1 && alias.charCodeAt(alias.length - 1) === 47) {
            alias = alias.slice(0, -1);
          }
          return alias;
        }

        function matchesBase(uri, base) {
          if (uri === base) {
            return true;
          }
          if (base === '/') {
            return uri === '/' || uri === '';
          }
          if (uri.length === base.length + 1 && uri.startsWith(base) && uri.charCodeAt(base.length) === 47) {
            return true;
          }
          return false;
        }

        function isDigit(code) {
          return code >= 48 && code <= 57;
        }

        function matchesExample(uri, base) {
          if (!uri.startsWith(base)) {
            return false;
          }
          var remainder = uri.slice(base.length);
          if (!remainder || remainder.charCodeAt(0) !== 47) {
            return false;
          }
          remainder = remainder.slice(1);
          if (!remainder) {
            return false;
          }
          if (remainder.charCodeAt(remainder.length - 1) === 47) {
            remainder = remainder.slice(0, -1);
          }
          if (remainder.length < 9) {
            return false;
          }
          var lowered = remainder.toLowerCase();
          if (lowered.slice(0, 8) !== 'eksempel') {
            return false;
          }
          var suffix = remainder.slice(8);
          if (!suffix) {
            return false;
          }
          var first = suffix.charCodeAt(0);
          if (first === 45 || first === 95) {
            suffix = suffix.slice(1);
          }
          if (!suffix) {
            return false;
          }
          for (var index = 0; index < suffix.length; index++) {
            if (!isDigit(suffix.charCodeAt(index))) {
              return false;
            }
          }
          return true;
        }

        function handler(event) {
          var request = event && event.request ? event.request : null;
          if (!request || typeof request.uri !== 'string') {
            return request;
          }

          var uri = request.uri;
          if (!uri) {
            return request;
          }

          var lowerUri = uri.toLowerCase();
          var routes = [
            { target: '/graftegner.html', aliases: ['/graftegner'], includeExamples: true },
            { target: '/nkant.html', aliases: ['/nkant'], includeExamples: true },
            { target: '/diagram/index.html', aliases: ['/diagram'], includeExamples: true },
            { target: '/brøkpizza.html', aliases: ['/br%C3%B8kpizza', '/brkpizza'], includeExamples: true },
            { target: '/brøkfigurer.html', aliases: ['/br%C3%B8kfigurer', '/brkfigurer'], includeExamples: true },
            { target: '/figurtall.html', aliases: ['/figurtall'], includeExamples: true },
            { target: '/tenkeblokker.html', aliases: ['/tenkeblokker'], includeExamples: true },
            { target: '/arealmodell.html', aliases: ['/arealmodell'], includeExamples: true },
            { target: '/tallinje.html', aliases: ['/tallinje'], includeExamples: true },
            { target: '/perlesnor.html', aliases: ['/perlesnor'], includeExamples: true },
            { target: '/kuler.html', aliases: ['/kuler'], includeExamples: true },
            { target: '/kvikkbilder.html', aliases: ['/kvikkbilder'], includeExamples: true },
            { target: '/kvikkbilder-monster.html', aliases: ['/kvikkbilder-monster'], includeExamples: true },
            { target: '/trefigurer.html', aliases: ['/trefigurer', '/3dfigurer'], includeExamples: true },
            { target: '/brøkvegg.html', aliases: ['/br%C3%B8kvegg', '/brkvegg'], includeExamples: true },
            { target: '/måling.html', aliases: ['/m%C3%A5ling', '/malingbeta'], includeExamples: false },
            { target: '/sortering.html', aliases: ['/sortering', '/sorteringbeta'], includeExamples: true, exampleTarget: '/index.html' },
            { target: '/prikktilprikk.html', aliases: ['/prikktilprikk', '/prikktilprikkbeta'], includeExamples: true },
            { target: '/fortegnsskjema.html', aliases: ['/fortegnsskjema', '/fortegnsskjemaunderutvikling'], includeExamples: true },
            { target: '/bibliotek.html', aliases: ['/bibliotek', '/bibliotekbeta'], includeExamples: true },
            { target: '/svg-arkiv.html', aliases: ['/svg-arkiv', '/eksempelarkiv'], includeExamples: false },
            { target: '/settings.html', aliases: ['/settings'], includeExamples: false }
          ];

          for (var i = 0; i < routes.length; i++) {
            var route = routes[i];
            var aliases = route.aliases;
            for (var j = 0; j < aliases.length; j++) {
              var normalized = normalizeAlias(aliases[j]);
              if (!normalized) {
                continue;
              }
              if (matchesBase(lowerUri, normalized)) {
                request.uri = route.target;
                return request;
              }
              if (route.includeExamples && matchesExample(lowerUri, normalized)) {
                request.uri = route.exampleTarget || route.target;
                return request;
              }
            }
          }

          return request;
        }

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        PriceClass: !Ref CloudFrontPriceClass
        DefaultRootObject: index.html
        HttpVersion: http2
        Comment: !Sub 'Math Visuals static site (${SiteEnvironmentName})'
        Origins:
          - Id: SiteBucketOrigin
            DomainName: !GetAtt SiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${SiteOriginAccessIdentity}'
          - Id: ApiGatewayOrigin
            DomainName: !Ref ApiGatewayDomainName
            OriginPath: !If [HasApiGatewayOriginPath, !Ref ApiGatewayOriginPath, !Ref "AWS::NoValue"]
            CustomOriginConfig:
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2
              HTTPPort: 80
              HTTPSPort: 443
        DefaultCacheBehavior:
          TargetOriginId: SiteBucketOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          Compress: true
          FunctionAssociations:
            - EventType: viewer-request
              FunctionARN: !GetAtt ViewerRequestRouterFunction.FunctionARN
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        # Place API-backed behaviors first so they receive higher precedence than
        # the static-site fallbacks in the CloudFront console. The deploy script
        # validates this ordering after every deployment and will reapply it if a
        # later console change moves /api/* below the default rule.
        CacheBehaviors:
          - PathPattern: '/api/*'
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: !Ref CachePolicyId
            OriginRequestPolicyId: !Ref ApiOriginRequestPolicy
          - PathPattern: '/bildearkiv/*'
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: !Ref CachePolicyId
            OriginRequestPolicyId: !Ref ApiOriginRequestPolicy
          - PathPattern: '/svg/*'
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: !Ref CachePolicyId
            OriginRequestPolicyId: !Ref ApiOriginRequestPolicy
          - PathPattern: '/figure-library/*'
            TargetOriginId: ApiGatewayOrigin
            ViewerProtocolPolicy: https-only
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            CachePolicyId: !Ref CachePolicyId
            OriginRequestPolicyId: !Ref ApiOriginRequestPolicy
          - PathPattern: '/figure-library/*.js'
            TargetOriginId: SiteBucketOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
          - PathPattern: '/sortering/eksempel*'
            TargetOriginId: SiteBucketOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
          - PathPattern: '/sortering*'
            TargetOriginId: SiteBucketOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
            CachedMethods:
              - GET
              - HEAD
            Compress: true
            ForwardedValues:
              QueryString: true
              Cookies:
                Forward: none
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
            ErrorCachingMinTTL: 0
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
      Tags:
        - Key: Environment
          Value: !Ref SiteEnvironmentName

Outputs:
  StaticSiteBucketName:
    Description: Name of the S3 bucket hosting the static site artifacts.
    Value: !Ref SiteBucket
    Export:
      Name: !Sub '${AWS::StackName}-StaticSiteBucketName'
  CloudFrontDistributionId:
    Description: Identifier of the CloudFront distribution serving the site.
    Value: !Ref Distribution
    Export:
      Name: !Sub '${AWS::StackName}-DistributionId'
  CloudFrontDistributionDomainName:
    Description: Domain name of the CloudFront distribution.
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: !Sub '${AWS::StackName}-DistributionDomainName'
  ExamplesAllowedOriginsParameterName:
    Description: Name of the shared SSM parameter used for EXAMPLES_ALLOWED_ORIGINS.
    Value: !ImportValue
      Fn::Sub: '${SharedParametersStackName}-ExamplesAllowedOriginsParameterName'
  SvgAllowedOriginsParameterName:
    Description: Name of the shared SSM parameter used for SVG_ALLOWED_ORIGINS.
    Value: !ImportValue
      Fn::Sub: '${SharedParametersStackName}-SvgAllowedOriginsParameterName'
